feature(backend): add GET /api/quizzes/{objectId} endpoint
teamfishydino/quizapp pull request #55
Opened 2024-09-16 07:06 UTC by acsolle66

This PR introduces a new API endpoint to fetch a quiz by its unique `ObjectId`. The endpoint returns a quiz document from the database if it exists and returns `404 Not Found` if no quiz matches the `ObjectId`.   

**Changes introduced:**
- Added a new route GET `/api/quizzes/{objectId}` to retrieve a quiz by its unique ID
- Integrated MongoDB query to fetch the quiz document based on the provided `ObjectId`
- Included unit tests to validate the endpoint's functionality

2024-09-17 11:43 UTC, rezbee-dev requested changes

2024-09-17 11:43 UTC, rezbee-dev commented on backend/tests/routers/test_quizzes.py
> +    response = test_client.get(f"/api/users/{fake_quiz_id}")
would this be the correct url? Should it be like `/api/quizzes/{fake_quiz_id}`?

2024-09-17 11:43 UTC, rezbee-dev commented on backend/quizapp/crud.py
> +    quiz = await quiz_collection.find_one({"_id": ObjectId(quiz_id)})
When inputting incorrect id, I get `500 - Internal Server error`, and this error message:
```py
| bson.errors.InvalidId: '66e965325edd25f2ddb1fab' is not a valid ObjectId
```

Maybe handle errors from `ObjectId()` and handle it to return `404` error instead?

2024-09-17 11:48 UTC, acsolle66 commented on backend/tests/routers/test_quizzes.py
> +    response = test_client.get(f"/api/users/{fake_quiz_id}")
Oh you are right, I was reading a guide and maybe copied this part and forgot to change it ...

2024-09-17 11:52 UTC, acsolle66 commented on backend/quizapp/crud.py
> +    quiz = await quiz_collection.find_one({"_id": ObjectId(quiz_id)})
Good idea. I will implement the error handling in my next commit.

2024-09-17 20:19 UTC, acsolle66 commented on backend/quizapp/crud.py
> +    quiz = await quiz_collection.find_one({"_id": ObjectId(quiz_id)})
I have chosen to raise `400 - Bad request` status code instead of `404 - Not found` and added meaningful messages to both.

2024-09-18 09:45 UTC, rezbee-dev commented on backend/tests/routers/test_quizzes.py
> +    response = test_client.get(f"/api/users/{fake_quiz_id}")
new changes LGTM

2024-09-18 09:46 UTC, rezbee-dev approved these changes

2024-09-18 09:46 UTC, merged